# Change these first
owner: durgeshbsb # Your GitHub organization or username, where this repository lives
repo: uptime_bsb # The name of this repository

sites:
  - name: Bsb fortrade website
    url: https://www.bsbfortrade.com
  - name: Swaarg AI
    url: https://swaarg.ai/chat
  - name: BSB Admin Panel + Mobile APIs
    url: https://bsbprime.bsbinfotrade.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 302
      - 300
      - 301
  - name: (DEMO) BSB Admin Panel + Mobile APIs
    url: https://bsbprimedemo.bsbinfotrade.com
    expectedStatusCodes:
      - 200
      - 201
      - 404
      - 302
      - 300
      - 301
  - name: Chantriq
    url: https://chantriq.com/
  - name: Backend NodeJS
    url: https://backend.bsbinfotrade.com/
  - name: Task Scheduler
    url: https://api-taskscheduler.bsbinfotrade.com/
  - name: (PORT) Backend NodeJS
    url: http://94.136.187.248:3000/
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime_bsb
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://bsbfortrade.com/assets/images/Logo_bsb_white.webp
  name: BSB
  introTitle: "**BSB Service Status**"
  introMessage: >
    Monitor the real-time availability and performance of BSB websites,
    applications, APIs, and customer services. This page is updated
    automatically to provide current operational status and incident history.
  navbar:
    - title: Status
      href: /
    # - title: GitHub
      # href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
